# Generated by Django 3.1.4 on 2020-12-14 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=12, null=True, unique=True)),
                ('inactive_player', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=12, null=True)),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='', max_length=12, unique=True)),
                ('host', models.CharField(max_length=50)),
                ('player_1', models.CharField(max_length=50, null=True)),
                ('player_2', models.CharField(max_length=50, null=True)),
                ('player_3', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
